# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = BioImageOperation
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -lopencv_core
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(BioImageOperation.pri)

# add open CV
unix {
    CONFIG += link_pkgconfig
    PKGCONFIG += opencv
}
